# Template generated code from trgen 0.15.2
default:
	rm -rf build; mkdir build; cd build; cmake .. -G "MSYS Makefiles"; $(MAKE)
run:
	cd build; ./Test.exe
clean:
	rm -rf build c:/temp/antlr4_runtime
